version: '2'

services:
    jobckr_webserver:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: jobckr_webserver
        ports:
            - ${WEBSERVER_PORT}:80
        volumes:
            - ../:/var/www/html/public
            - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf
        restart: always
        depends_on:
            - jobckr_mysql
            - jobckr_redis

    jobckr_mysql:
        image: mysql:5.7
        container_name: jobckr_mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306

    jobckr_redis:
        image: redis:4.0.5-alpine
        container_name: jobckr_redis
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
        restart: always
        ports:
            - ${REDIS_PORT}:6379
